//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, inject, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase, HttpContext } from '@angular/common/http';

export const WEB_API_BASE_URL = new InjectionToken<string>('WEB_API_BASE_URL');

export interface IClient {
  /**
 * List all clients accounts
 * @return Success
 */
  bcsvisasApplicationsServerUsersEndpointsClientsQueriesListClients(): Observable<BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse>;
}

@Injectable()
export class Client implements IClient {
  private http: HttpClient = inject(HttpClient);
  private baseUrl: string = inject(WEB_API_BASE_URL);
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  /**
 * List all clients accounts
 * @return Success
 */
  bcsvisasApplicationsServerUsersEndpointsClientsQueriesListClients(httpContext?: HttpContext): Observable<BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse> {
    let url_ = this.baseUrl + "/users/clients";
    url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            context: httpContext,
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processBcsvisasApplicationsServerUsersEndpointsClientsQueriesListClients(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processBcsvisasApplicationsServerUsersEndpointsClientsQueriesListClients(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse>;
        }));
    }

  protected processBcsvisasApplicationsServerUsersEndpointsClientsQueriesListClients(response: HttpResponseBase): Observable<BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse> {
    const status = response.status;
    const responseBlob = response instanceof HttpResponse
      ? response.body
      : (response as any).error instanceof Blob ? (response as any).error : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
        }
      }
    if (status === 200) {
        return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        let result200: any = null;
        let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse.fromJS(resultData200);
        return _observableOf(result200);
        }));
    } else if (status === 400) {
        return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        let result400: any = null;
        let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
        result400 = FastEndpointsProblemDetails.fromJS(resultData400);
        return throwException("Bad Request", status, _responseText, _headers, result400);
        }));
    } else if (status !== 200 && status !== 204) {
    return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
          return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }));
    }
    return _observableOf(null as any);
  }
}

export class BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse implements IBcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse {

    constructor(data?: IBcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IBcsvisasApplicationsServerUsersEndpointsClientsQueriesListClientsResponse {
}

/** RFC7807 compatible problem details/ error response class. this can be used by configuring startup like so: app.UseFastEndpoints(c => c.Errors.UseProblemDetails()) */
export class FastEndpointsProblemDetails implements IFastEndpointsProblemDetails {
    type?: string;
    title?: string;
    status?: number;
    instance?: string;
    traceId?: string;
    /** the details of the error */
    detail?: string | undefined;
    errors?: FastEndpointsProblemDetails_Error[];

    constructor(data?: IFastEndpointsProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.type = "https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1";
            this.title = "One or more validation errors occurred.";
            this.status = 400;
            this.instance = "/api/route";
            this.traceId = "0HMPNHL0JHL76:00000001";
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"] !== undefined ? _data["type"] : "https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1";
            this.title = _data["title"] !== undefined ? _data["title"] : "One or more validation errors occurred.";
            this.status = _data["status"] !== undefined ? _data["status"] : 400;
            this.instance = _data["instance"] !== undefined ? _data["instance"] : "/api/route";
            this.traceId = _data["traceId"] !== undefined ? _data["traceId"] : "0HMPNHL0JHL76:00000001";
            this.detail = _data["detail"];
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(FastEndpointsProblemDetails_Error.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FastEndpointsProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new FastEndpointsProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["instance"] = this.instance;
        data["traceId"] = this.traceId;
        data["detail"] = this.detail;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

/** RFC7807 compatible problem details/ error response class. this can be used by configuring startup like so: app.UseFastEndpoints(c => c.Errors.UseProblemDetails()) */
export interface IFastEndpointsProblemDetails {
    type?: string;
    title?: string;
    status?: number;
    instance?: string;
    traceId?: string;
    /** the details of the error */
    detail?: string | undefined;
    errors?: FastEndpointsProblemDetails_Error[];
}

/** the error details object */
export class FastEndpointsProblemDetails_Error implements IFastEndpointsProblemDetails_Error {
    /** the name of the error or property of the dto that caused the error */
    name?: string;
    /** the reason for the error */
    reason?: string;
    /** the code of the error */
    code?: string | undefined;
    /** the severity of the error */
    severity?: string | undefined;

    constructor(data?: IFastEndpointsProblemDetails_Error) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.name = "Error or field name";
            this.reason = "Error reason";
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"] !== undefined ? _data["name"] : "Error or field name";
            this.reason = _data["reason"] !== undefined ? _data["reason"] : "Error reason";
            this.code = _data["code"];
            this.severity = _data["severity"];
        }
    }

    static fromJS(data: any): FastEndpointsProblemDetails_Error {
        data = typeof data === 'object' ? data : {};
        let result = new FastEndpointsProblemDetails_Error();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["reason"] = this.reason;
        data["code"] = this.code;
        data["severity"] = this.severity;
        return data;
    }
}

/** the error details object */
export interface IFastEndpointsProblemDetails_Error {
    /** the name of the error or property of the dto that caused the error */
    name?: string;
    /** the reason for the error */
    reason?: string;
    /** the code of the error */
    code?: string | undefined;
    /** the severity of the error */
    severity?: string | undefined;
}

export interface FileParameter {
    data: any;
    fileName: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}